### GENERAL SETTINGS ###

# Site settings
title: ~ ⟩ Bennett Computational Hydrology Lab
about: 
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl:  "" #important: start with /
url: "https://uw-hydro.github.io/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#4b2e83" #"#00b3fe" #"#F70031"
  primary_rgb: "51,0,111" #"0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#b7a57a" #e8e3d3" #"#85754d" #"#384452" #"#33004D"
  link: "#4b2e83" #"#428bca"
  link_hover: "#85754d"#"#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#ffffff" #d9d9d9" #"#bfc9d3"
  text: "#444444"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
online:
  - title: github
    url: https://github.com/UW-Hydro
  # - title: facebook
  #   url: https://github.com/UW-Hydro
  # - title: twitter
  #   url:
  # - title: instagram
  #   url:
  # - title: tumblr
  #   url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Tucson, Arizona
